$terminal = alacritty
$fileManager = thunar
$menu = wofi --show drun --insensitive true

$screenshot_save = grim -g "$(slurp)" "$(zenity --file-selection --save --confirm-overwrite --filename="$HOME/screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png")"
$screenshot_copy = grim -g "$(slurp)" - | wl-copy

$pick_color = hyprpicker | wl-copy

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = AQ_DRM_DEVICES,/dev/dri/nvidia-gpu:/dev/dri/intel-igpu
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GL_GSYNC_ALLOWED,0
env = __GL_VRR_ALLOWED,0
